authors:
  miggi92:
    name: Miguel Gebhardt
    title: ABAP Developer
    description: Creator
    url: https://github.com/miggi92
    avatar: https://github.com/miggi92.png
  mGebAtBechtle:
    name: Miguel
    title: ABAP Developer
    description: Contributor
    url: https://github.com/mGebAtBechtle
    avatar: https://github.com/mGebAtBechtle.png